kvik_admin_index:
    path:     /
    defaults: { _controller: KvikAdminBundle:Admin:index }

#Terms
kvik_admin_terms:
    path:    /{type}
    defaults:
        _controller: KvikAdminBundle:Term:index
    requirements:
        type: categories|tags
kvik_admin_term_edit:
    path:    /{type}/edit-{id}
    defaults:
        _controller: KvikAdminBundle:Term:edit
    requirements:
        type: categories|tags
        id: \d+
kvik_admin_term_delete:
    path:    /{type}/delete-{id}
    defaults:
        _controller: KvikAdminBundle:Term:delete
    requirements:
        type: categories|tags
        id: \d+

#Post
kvik_admin_post:
    path:    /posts-{type}
    defaults:
        _controller: KvikAdminBundle:Post:index
        type: post
    requirements:
        type: post|page
kvik_admin_post_add:
    path:    /post/create-{type}
    defaults:
        _controller: KvikAdminBundle:Post:add
        type: post
    requirements:
        type: post|page

#User
kvik_admin_users:
    path:    /users
    defaults:
        _controller: KvikAdminBundle:User:index
kvik_admin_user_add:
    path:    /user/add
    defaults:
        _controller: KvikAdminBundle:User:add
kvik_admin_user_edit:
    path:    /user/edit-{id}
    defaults:
        _controller: KvikAdminBundle:User:edit
    requirements:
        id: \d+
kvik_admin_user_delete:
    path:    /user/delete-{id}
    defaults:
        _controller: KvikAdminBundle:User:delete
    requirements:
        id: \d+


#FOS User routes
fos_user_profile_edit:
    path: /profile/edit
    defaults:
        _controller: KvikAdminBundle:User:edit
